export const GET_ERRORS = "GET_ERRORS";

// History event
export const GET_HISTORY_EVENTS = "GET_HISTORY_EVENTS";
export const DELETE_HISTORY_EVENT = "DELETE_HISTORY_EVENT";
export const CREATE_HISTORY_EVENT = "CREATE_HISTORY_EVENT";

// Event color
export const REASSIGN_ALL_EVENT_COLORS = "REASSIGN_ALL_EVENT_COLORS";
export const DELETE_EVENT_COLOR_PAIR = "DELETE_EVENT_COLOR_PAIR";
export const ASSIGN_EVENT_COLOR_PAIR = "ASSIGN_EVENT_COLOR_PAIR";

// Selected Event
export const SELECT_HISTORY_EVENT = "SELECT_HISTORY_EVENT";
export const DESELECT_HISTORY_EVENT = "DESELECT_HISTORY_EVENT";
export const SINGLE_SELECT_HISTORY_EVENT = "SINGLE_SELECT_HISTORY_EVENT";
export const DESELECT_ALL_HISTORY_EVENTS = "DESELECT_ALL_HISTORY_EVENT";
